### ISSUE TITLE
Css-porperties

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/all-human-accessible-website#10]
Er is nog steeds herhaalde code aanwezig. Overweeg welke elementen dezelfde CSS-properties kunnen delen en maak daarvoor een gemeenschappelijke class. Specifieke wijzigingen (zoals in het voorbeeld van `hover` hieronder) kunnen dan met een extra class of een andere selector/state worden overschreven.

Je kunt de grid-implementatie vereenvoudigen door `repeat` te gebruiken:
```css
body {
  grid-template-columns: repeat(5, 1fr);
  grid-template-rows: repeat(8, 1fr);
}
```
