### ISSUE TITLE
like:hover

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/all-human-accessible-website#11]
Denk erover om herhaalde code te vereenvoudigen. Dit zou de leesbaarheid en efficiëntie van je CSS kunnen verbeteren. Het is waarschijnlijk niet nodig om alle properties voor like:hover op te nemen:

```css
.like {
  position: relative;
  justify-self: right;
  grid-area: like;
  background-color: lime;
  border-radius: 50%;
  right: 0;
  width: 1.5em;
  height: 1.5em;
  margin-right: 1em;
  margin-top: 1em;
}

.like:hover, .like:focus {
  background-color: red;
}
```
